/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author hacker
 */
public class myCalculator extends javax.swing.JPanel {

    /**
     * Creates new form myCalculator
     */
    public static void main (String args[]){
        
   
}
 public myCalculator() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();

        setDoubleBuffered(false);
        setEnabled(false);
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(369, 322));
        setPreferredSize(new java.awt.Dimension(385, 332));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 12, 339, 71));

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton1.setText("7");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 101, 47, -1));

        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton2.setText("8");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 101, 51, -1));

        jButton3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton3.setText("9");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 101, 50, -1));

        jButton4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton4.setText("/");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 101, 48, -1));

        jButton5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton5.setText("<--");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 101, 48, -1));

        jButton6.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton6.setText("c");
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 101, 48, -1));

        jButton7.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton7.setText("4");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 161, 47, -1));

        jButton8.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton8.setText("5");
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 161, 51, -1));

        jButton9.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton9.setText("6");
        add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 161, 50, -1));

        jButton10.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton10.setText("*");
        add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 161, 48, -1));

        jButton11.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton11.setText("^3");
        add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 161, 48, -1));

        jButton12.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton12.setText("^2");
        add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 161, 48, -1));

        jButton13.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton13.setText("1");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 221, 47, -1));

        jButton14.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton14.setText("2");
        add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 221, 51, -1));

        jButton15.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton15.setText("3");
        add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 221, 50, -1));

        jButton16.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton16.setText("-");
        add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 221, 48, -1));

        jButton17.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton17.setText(">2");
        add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 221, 48, -1));

        jButton18.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton18.setText(">3");
        add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 221, 48, -1));

        jButton19.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton19.setText("0");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 282, 47, -1));

        jButton20.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton20.setText(".");
        add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 282, 51, -1));

        jButton21.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton21.setText("%");
        add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 282, 50, -1));

        jButton22.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton22.setText("+");
        add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 282, 48, -1));

        jButton23.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton23.setText("=");
        add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 282, 100, -1));

        jButton24.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton24.setText("c");
        add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 101, 48, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String enterNumber = jTextField1.getText() +jButton1.getText();
        jTextField1.setText(enterNumber);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
